const itemsArray=["Hamburger",
  "Cheeseburger",
  "Sandwich",
  "Milk shake",
  "Muffin",
  "Burrito",
  "Biscuit",
  "Taco",
  "Hot dog",
  "Fried chicken",
  "Donuts",
  "Baguette",
  "Soft drink",
  "Pizza",
  "Onion ring",
  "Sausage",
  "Pretzel",
  "Pancake",
  "Bacon",
  "Chip",
  "Noodle",
"Chowmein",
"Butter Chips",
"Sandwich",
"Masala Dosa",
"Rawa Dosa",
"Paneer Dosa"]
export default itemsArray